# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NwbRY8nKy1DqBchVv5wt44VfhCK9Fx6z
"""

def kasallik_tashxis(alomat):
    if alomat == "bosh og'riq, isitma ":
      return "Sizda gripp belgilari bor"
    elif alomat == "qorin og'riqi ":
      return "Sizda spazma bor"
    elif alomat == "tish og'riqi":
      return "Stamatolikka murojat qiling"
    elif alomat == "bo'g'in  og'riqi ":
      return "Ketanal krim suring"
    elif alomat == "oyoq sinishi ":
      return "Terapekga murojat qilling"
    elif alomat == "yurak sanchishi":
      return "Kardiolikka murojat qiling"
    elif alomat == "tez tez og'iz qurishi ":
      return "Sizda qantli diabit bulishi mumkin"
    elif alomat == "nafas olishda qiynalish":
      return "Sizda burun shomollash alomati bor"
    else:
      return "Shifokorga murojat qiling "
alomat =input("Belgini kiriting ")
natija =kasallik_tashxis(alomat)
print(natija)

def mashinalr_tarixi(nomi):
    if nomi == "Mercedes-Benz":
      return "1926-yil Germaniya"
    elif nomi == "BMW":
      return "1928-yil Germaniyada"
    elif nomi == "Ford":
      return "1908-yil Italiya"
    elif nomi == "Chevralet":
      return "1911-yil AQSh"
    elif nomi== "Ferrari":
      return "1947-yil Maranello"
    elif nomi == "Lambarghini":
      return "1963-yil Italiya"
    elif nomi == "Rolls-Royce":
      return "1904-yil Angilya"
    elif nomi == "Toyoto":
      return "1937-yil Yaponiya"
    elif nomi == "Audi":
      return "1969-yil Italiya"
    elif nomi == "Tesla":
      return "2003-yil AQSh"
    elif nomi == "Daewoo":
      return "1937-yil Janubiy Kareya"
    else:
      return "Bunaqa markali mashina haqida bazadan malumot topilmadi "
nomi =input("Nomini kiriting ")
natija =mashinalr_tarixi(nomi)
print(natija)